services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: node app/app.js
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: admin
      MYSQL_PASS: password
      MYSQL_DATABASE: sd2-db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sd2-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: password
    ports:
      - "8083:80"